/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "BlocoPWM2.h"
#include "QuadDec2.h"
#include "QuadDec2_PVT.h"
#include "qa2_aliases.h"
#include "qa2.h"
#include "qb2_aliases.h"
#include "qb2.h"
#include "Clock_1.h"
#include "pwm2_aliases.h"
#include "pwm2.h"
#include "UART.h"
#include "dir2_aliases.h"
#include "dir2.h"
#include "slp2_aliases.h"
#include "slp2.h"
#include "BlocoPWM1.h"
#include "QuadDec1.h"
#include "QuadDec1_PVT.h"
#include "qa1_aliases.h"
#include "qa1.h"
#include "qb1_aliases.h"
#include "qb1.h"
#include "pwm1_aliases.h"
#include "pwm1.h"
#include "slp1_aliases.h"
#include "slp1.h"
#include "BlocoPWM3.h"
#include "QuadDec3.h"
#include "QuadDec3_PVT.h"
#include "qa3_aliases.h"
#include "qa3.h"
#include "qb3_aliases.h"
#include "qb3.h"
#include "pwm3_aliases.h"
#include "pwm3.h"
#include "dir3_aliases.h"
#include "dir3.h"
#include "slp3_aliases.h"
#include "slp3.h"
#include "TimerMotores.h"
#include "isr_timer_motores.h"
#include "led_aliases.h"
#include "led.h"
#include "timer_clock_1.h"
#include "TimerCinematico.h"
#include "isr_timer_cinematico.h"
#include "dir1_aliases.h"
#include "dir1.h"
#include "CANRX_aliases.h"
#include "CANRX.h"
#include "CANTX_aliases.h"
#include "CANTX.h"
#include "CAN.h"
#include "QuadDec2_isr.h"
#include "QuadDec2_Cnt16.h"
#include "UART_IntClock.h"
#include "QuadDec1_isr.h"
#include "QuadDec1_Cnt16.h"
#include "QuadDec3_isr.h"
#include "QuadDec3_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

